---
abstract: 'A collection of modules removed from Module-Build'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Build-Deprecated
provides:
  Module::Build::Deprecated:
    file: lib/Module/Build/Deprecated.pm
    version: '0.002'
  Module::Build::ModuleInfo:
    file: lib/Module/Build/ModuleInfo.pm
    version: '0.002'
  Module::Build::Version:
    file: lib/Module/Build/Version.pm
    version: '0.002'
  Module::Build::YAML:
    file: lib/Module/Build/YAML.pm
    version: '0.002'
requires:
  CPAN::Meta::YAML: '0.002'
  Module::Metadata: '0'
  base: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  version: '0.87'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Build-Deprecated
  repository: git://github.com/Leont/module-build-deprecated.git
version: '0.002'
